### ISSUE TITLE
Error on integration init AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'.

### ISSUE THREAD

**Issue by daveedwards123** [TimSoethout/goodwe-sems-home-assistant#130]
After updating to 2025.6 i am getting this error:

`Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 9:23:18 PM (3 occurrences)
Last logged: 9:43:29 PM

Error setting up entry 4f97833b-b845-4b9a-86e5-b8c29fb4b705 for sems
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sems/__init__.py", line 38, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?`

After some googling, i found a very similar issue: https://github.com/albertogeniola/meross-homeassistant/issues/552

Would someone be able to update?

Thanks

**Comment by SMac3265** [comment]
I just updated to the newest HA Core, and am receiving this same error. After some research, this is what I was able to find:

"This is a breaking change in Home Assistant Core 2024.6, which removed async_forward_entry_setup() in favor of the plural async_forward_entry_setups(). This breaks custom components that haven't been updated yet."

So, it appears this integration will need to be repaired to work with the new HA Core.

Sean

**Comment by TimSoethout** [comment]
Please install 7.2.0 (non-beta) and see if this fixes it for you.

There might be other breaking changes w.r.t. entity names and id's. 
Let me know if any issues arise.

**Comment by daveedwards123** [comment]
The good news is that 7.2.0 allowed the integration to start.
Looks like the inverter is recording correctly as i can see solar generation stats.

The bad news is that the homekit is not working, no import/export from grid.

![Image](https://github.com/user-attachments/assets/b47ac6cd-acee-43a4-a1e2-8583483ea16f)

I am seeing this in the logs now:

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 180, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1019, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1141, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1081, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/sems/sensor.py", line 311, in state
    return data["etotal"]
           ~~~~^^^^^^^^^^
KeyError: 'etotal'

**Comment by TimSoethout** [comment]
Can you try 7.3.0-beta with extra debug logging around etotal?
Not sure what is going on, and hard for me to debug since I don't have a HomeKit.

Maybe we should move the discussion to a new issue, or #133 In TimSoethout/goodwe-sems-home-assistant;

**Comment by daveedwards123** [comment]
Moved to https://github.com/TimSoethout/goodwe-sems-home-assistant/issues/133
Thanks
