### ISSUE TITLE
unexpected keyword argument 'config_entry'

### ISSUE THREAD

**Issue by earvingad** [TimSoethout/goodwe-sems-home-assistant#139]
Updated to last version, however cannot set the inverter. It was working with version 6.1.

I am using HA Core 2024.10.3

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 1:30:05 PM (1 occurrences)
Last logged: 1:30:05 PM

Error setting up entry Inverter "ID"  for sems
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sems/__init__.py", line 41, in async_setup_entry
    coordinator = SemsDataUpdateCoordinator(hass, semsApi, entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sems/__init__.py", line 131, in __init__
    super().__init__(
TypeError: DataUpdateCoordinator.__init__() got an unexpected keyword argument 'config_entry'
```

**Comment by dh0llyw00d** [comment]
I think this was fixed by release 7.4.1, updating to the latest release fixed it for me.

**Comment by TodaysSawyer** [comment]
Facing the same issue over here; attempting to connect for the first time on a clean install of everything. Docker HA - Official image, fresh HACS, 7.4.1 of this integation

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sems/__init__.py", line 41, in async_setup_entry
    coordinator = SemsDataUpdateCoordinator(hass, semsApi, entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sems/__init__.py", line 131, in __init__
    super().__init__(
TypeError: DataUpdateCoordinator.__init__() got an unexpected keyword argument 'config_entry'
